---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: e2e-main-pipeline
  namespace: rhtap-shared-team-tenant
  labels:
    appstudio.openshift.io/component: rhtap-cli
    appstudio.openshift.io/application: rhtap-cli
spec:
  params:
    - name: SNAPSHOT
      description: 'The JSON string representing the snapshot of the application under test.'
      default: '{"components": [{"name":"test-app", "containerImage": "quay.io/example/repo:latest"}]}'
      type: string
    - name: konflux-test-infra-secret
      description: The name of secret where testing infrastructures credentials are stored.
      type: string
  tasks:
    - name: test-metadata
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/konflux-ci/konflux-qe-definitions.git
          - name: revision
            value: main
          - name: pathInRepo
            value: common/tasks/test-metadata/0.2/test-metadata.yaml
      params:
        - name: SNAPSHOT
          value: $(params.SNAPSHOT)
        - name: test-name
          value: $(context.pipelineRun.name)
    - name: get-pict-file
      runAfter:
        - test-metadata
      taskSpec:
        results:
          - name: pict-file
            description: pict file to be used in next step
        steps:
          - name: download
            image: quay.io/konflux-ci/appstudio-utils:ab6b0b8e40e440158e7288c73aff1cf83a2cc8a9@sha256:24179f0efd06c65d16868c2d7eb82573cce8e43533de6cea14fec3b7446e0b14
            env:
              - name: JOB_SPEC
                value: $(tasks.test-metadata.results.job-spec)
            script: |
              #!/usr/bin/env bash
              GIT_REPO="$(jq -r '.git.repo // empty' <<< $JOB_SPEC)"

              if [[ "${GIT_REPO}" = "rhtap-cli" ]]; then
                REPO_ORG=$(jq -r '.git.source_repo_org' <<< $JOB_SPEC)
                BRANCH=$(jq -r '.git.source_repo_branch' <<< $JOB_SPEC)
              else
                REPO_ORG="redhat-appstudio"
                BRANCH="main"
              fi
              curl -o $(results.pict-file.path) https://raw.githubusercontent.com/$REPO_ORG/rhtap-cli/refs/heads/$BRANCH/integration-tests/pict-models/default.pict
    - name: generate-configs
      runAfter:
        - get-pict-file
      taskSpec:
        results:
          - name: configs-json
            description: Config json generated from pict file.
        steps:
          - name: pict-generate
            image: quay.io/apodhrad/pict:latest
            script: |
              #!/usr/bin/env bash
              echo "$(tasks.get-pict-file.results.pict-file)" > main.pict
              cat main.pict
              pict ./main.pict -o:2 -f:json > $(results.configs-json.path)
    - name: start-nested-pipelines
      params:
        - name: job-spec
          value: "$(tasks.test-metadata.results.job-spec)"
      runAfter:
        - test-metadata
        - generate-configs
      taskSpec:
        steps:
          - name: start-pipeline
            image: quay.io/openshift-pipeline/ci
            env:
              - name: SNAPSHOT
                value: $(params.SNAPSHOT)
              - name: JOB_SPEC
                value: $(tasks.test-metadata.results.job-spec)
              - name: CONFIGS_JSON
                value: $(tasks.generate-configs.results.configs-json)
              - name: KONFLUX_APPLICATION_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['appstudio.openshift.io/application']
              - name: KONFLUX_COMPONENT_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['appstudio.openshift.io/component']
            script: |
              #!/usr/bin/env bash
              set -euxo pipefail

              GIT_REPO="$(jq -r '.git.repo // empty' <<< $JOB_SPEC)"

              if [[ "${GIT_REPO}" = "rhtap-cli" ]]; then
                REPO_ORG=$(jq -r '.git.source_repo_org' <<< $JOB_SPEC)
                BRANCH=$(jq -r '.git.source_repo_branch' <<< $JOB_SPEC)
              else
                REPO_ORG="redhat-appstudio"
                BRANCH="main"
              fi

              echo "Running tests for OCP versions:"
              echo "$CONFIGS_JSON" | jq -r '.[][] | select(.key == "OCP").value'

              pids=()

              while IFS=$'\n' read -r values; do
                (
                version="$(echo $values | jq -r '.[] | select(.key == "OCP") | .value')"
                acs_config="$(echo $values | jq -r '.[] | select(.key == "ACS") | .value')"
                acs=$([[ "$acs_config" =~ "deploy" ]] && echo "acs-deploy" || echo "acs-hosted")
                pipeline_run_name=$(tkn pipeline start -f https://raw.githubusercontent.com/$REPO_ORG/rhtap-cli/refs/heads/$BRANCH/integration-tests/pipelines/rhtap-cli-e2e.yaml \
                  --param ocp-version="$version"\
                  --param acs_config="$acs_config" \
                  --param job-spec="$JOB_SPEC"\
                  --param konflux-test-infra-secret="$(params.konflux-test-infra-secret)" \
                  --use-param-defaults \
                  --labels "appstudio.openshift.io/component=${KONFLUX_COMPONENT_NAME}" \
                  --labels "appstudio.openshift.io/application=${KONFLUX_APPLICATION_NAME}" \
                  --labels "pipelines.appstudio.openshift.io/type=$(context.pipelineRun.name)" \
                  --labels "test.appstudio.openshift.io/scenario=pr-e2e-tests" \
                  --prefix-name "e2e-$version-$acs"\
                  -o name)

                  tkn pipelinerun logs  "$pipeline_run_name" -f | sed "s/^/$pipeline_run_name: /"

                  pipelinerun_status=$(tkn pipelinerun describe "$pipeline_run_name" -o jsonpath='{.status.conditions[0].status}')
                  if [ "$pipelinerun_status" != "True" ]; then
                    echo "Pipelinerun $pipeline_run_name failed"
                    exit 1
                  fi

                ) &
                pid="$!"
                pids+=("$pid")
              done < <(echo "$CONFIGS_JSON" | jq -c '.[]')

              for pid in "${pids[@]}"; do
                wait "$pid"
                return_code=$?
                if [ $return_code -ne 0 ]; then
                  echo "One or more pipelineruns failed. Exiting with non-zero code."
                  oc get pipelineruns
                  exit 1
                fi
              done
